// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqSdncTn0kaDWIvors2v1BuYLHO93rmw',
    appId: '1:180598141198:web:808cddbc4252b4cd18e75f',
    messagingSenderId: '180598141198',
    projectId: 'fitcore-dd584',
    authDomain: 'fitcore-dd584.firebaseapp.com',
    storageBucket: 'fitcore-dd584.firebasestorage.app',
    measurementId: 'G-SM787N5F0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AuL67maZeGuPqGG1wFSxPgdJzjWFB-Q',
    appId: '1:180598141198:android:4a6698fc5e0a5d3218e75f',
    messagingSenderId: '180598141198',
    projectId: 'fitcore-dd584',
    storageBucket: 'fitcore-dd584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2B4xU9BPUJxUXPXwTN4qcylE7SHeqZ0',
    appId: '1:180598141198:ios:fab6e22753eb573218e75f',
    messagingSenderId: '180598141198',
    projectId: 'fitcore-dd584',
    storageBucket: 'fitcore-dd584.firebasestorage.app',
    iosClientId: '180598141198-q25dvq0hh2ouvknu172h2f8ruh5q2a8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ2B4xU9BPUJxUXPXwTN4qcylE7SHeqZ0',
    appId: '1:180598141198:ios:fab6e22753eb573218e75f',
    messagingSenderId: '180598141198',
    projectId: 'fitcore-dd584',
    storageBucket: 'fitcore-dd584.firebasestorage.app',
    iosClientId: '180598141198-q25dvq0hh2ouvknu172h2f8ruh5q2a8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWqSdncTn0kaDWIvors2v1BuYLHO93rmw',
    appId: '1:180598141198:web:6d7014a2c921045d18e75f',
    messagingSenderId: '180598141198',
    projectId: 'fitcore-dd584',
    authDomain: 'fitcore-dd584.firebaseapp.com',
    storageBucket: 'fitcore-dd584.firebasestorage.app',
    measurementId: 'G-E13ZEQ37SR',
  );
}
